# Move focus
unbind = SUPER, LEFT
unbind = SUPER, RIGHT
unbind = SUPER, UP
unbind = SUPER, DOWN

unbind = SUPER, H
unbind = SUPER, L
unbind = SUPER, K
unbind = SUPER, J

bindd = SUPER, H, Focus left window, movefocus, l
bindd = SUPER, L, Focus right window, movefocus, r
bindd = SUPER, K, Focus up window, movefocus, u
bindd = SUPER, J, Focus down window, movefocus, d

# Move window
unbind = SUPER SHIFT, H
unbind = SUPER SHIFT, L
unbind = SUPER SHIFT, K
unbind = SUPER SHIFT, J

unbind = SUPER SHIFT, LEFT
unbind = SUPER SHIFT, RIGHT
unbind = SUPER SHIFT, UP
unbind = SUPER SHIFT, DOWN

bindd = SUPER SHIFT, H, Move window to the left, movewindow, l
bindd = SUPER SHIFT, L, Move window to the right, movewindow, r
bindd = SUPER SHIFT, K, Move window up, movewindow, u
bindd = SUPER SHIFT, J, Move window down, movewindow, d

# Apps
unbind = SUPER SHIFT, F
unbind = SUPER SHIFT, T
unbind = SUPER SHIFT, B
unbind = SUPER SHIFT, S

bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- kitty -e yazi
bindd = SUPER SHIFT, T, BTOP, exec, uwsm-app -- kitty -e btop
bindd = SUPER SHIFT, B, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, S, Music, exec, omarchy-launch-or-focus spotify

# Websites
unbind = SUPER SHIFT, C
unbind = SUPER SHIFT, M
unbind = SUPER SHIFT, A
unbind = SUPER SHIFT, N
unbind = SUPER SHIFT, O

bindd = SUPER SHIFT, C, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
bindd = SUPER SHIFT, M, Email, exec, omarchy-launch-webapp "https://https://mail.google.com/mail"
bindd = SUPER SHIFT, A, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
bindd = SUPER SHIFT, N, Notion, exec, omarchy-launch-webapp "https://notion.com"
bindd = SUPER SHIFT, O, AoPS Community, exec, omarchy-launch-webapp "https://artofproblemsolving.com/community/c13_contests"

# Utilities
unbind = SUPER, E
unbind = SUPER, Q
unbind = SUPER, R
unbind = SUPER, N
unbind = SUPER, T
unbind = SUPER, Y
unbind = SUPER, U
unbind = SUPER, I
unbind = SUPER, O
unbind = SUPER, P
unbind = SUPER, A
unbind = SUPER, S
unbind = SUPER, D
unbind = SUPER, G
unbind = SUPER, Z
unbind = SUPER, X
unbind = SUPER, C
unbind = SUPER, V
unbind = SUPER, B
unbind = SUPER, M

bindd = SUPER, E, Emoji picker, exec, omarchy-launch-walker -m symbols
bindd = SUPER, Q, Screenshot, exec, omarchy-capture-screenshot
bindd = SUPER, R, Show key bindings, exec, omarchy-menu-keybindings
bindd = SUPER, N, Toggle nightlight, exec, omarchy-toggle-nightlight
