# Move focus
unbind = SUPER, LEFT
unbind = SUPER, RIGHT
unbind = SUPER, UP
unbind = SUPER, DOWN

unbind = SUPER, H
unbind = SUPER, L
unbind = SUPER, K
unbind = SUPER, J

bindd = SUPER, H, Focus left window, movefocus, l
bindd = SUPER, L, Focus right window, movefocus, r
bindd = SUPER, K, Focus up window, movefocus, u
bindd = SUPER, J, Focus down window, movefocus, d

# Move window
unbind = SUPER SHIFT, H
unbind = SUPER SHIFT, L
unbind = SUPER SHIFT, K
unbind = SUPER SHIFT, J

unbind = SUPER SHIFT, LEFT
unbind = SUPER SHIFT, RIGHT
unbind = SUPER SHIFT, UP
unbind = SUPER SHIFT, DOWN

bindd = SUPER SHIFT, H, Move window to the left, movewindow, l
bindd = SUPER SHIFT, L, Move window to the right, movewindow, r
bindd = SUPER SHIFT, K, Move window up, movewindow, u
bindd = SUPER SHIFT, J, Move window down, movewindow, d

# Apps
unbind = SUPER SHIFT, Q 
unbind = SUPER SHIFT, W
unbind = SUPER SHIFT, E
unbind = SUPER SHIFT, R
unbind = SUPER SHIFT, T #
unbind = SUPER SHIFT, Y
unbind = SUPER SHIFT, U
unbind = SUPER SHIFT, I
unbind = SUPER SHIFT, O #
unbind = SUPER SHIFT, P
unbind = SUPER SHIFT, A #
unbind = SUPER SHIFT, S #
unbind = SUPER SHIFT, D #
unbind = SUPER SHIFT, F #
unbind = SUPER SHIFT, G #
unbind = SUPER SHIFT, Z
unbind = SUPER SHIFT, X
unbind = SUPER SHIFT, C #
unbind = SUPER SHIFT, V
unbind = SUPER SHIFT, B #
unbind = SUPER SHIFT, N #
unbind = SUPER SHIFT, M #

bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, T, BTOP, exec, uwsm-app -- kitty -e btop
bindd = SUPER SHIFT, O, AoPS Community, exec, omarchy-launch-webapp "https://artofproblemsolving.com/community/c13_contests"
bindd = SUPER SHIFT, A, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
bindd = SUPER SHIFT, S, Music, exec, omarchy-launch-or-focus spotify
# bindd = SUPER SHIFT, D, Discord, exec, omarchy-launch-webapp "https://discord.com/channels/@me"
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- kitty -e yazi
bindd = SUPER SHIFT, G, Github, exec, omarchy-launch-webapp "https://github.com"
bindd = SUPER SHIFT, C, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
bindd = SUPER SHIFT, B, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, N, Notion, exec, omarchy-launch-webapp "https://app.notion.com"
bindd = SUPER SHIFT, M, Email, exec, omarchy-launch-webapp "https://mail.google.com/mail"

# Utilities
unbind = SUPER, Q #
unbind = SUPER, E #
unbind = SUPER, R #
unbind = SUPER, T
unbind = SUPER, Y
unbind = SUPER, U
unbind = SUPER, I #
unbind = SUPER, O
unbind = SUPER, P #
unbind = SUPER, A
unbind = SUPER, S
unbind = SUPER, D
unbind = SUPER, G
unbind = SUPER, Z
unbind = SUPER, X
unbind = SUPER, C #
unbind = SUPER, V
unbind = SUPER, B #
unbind = SUPER, N #
unbind = SUPER, M #

bindd = SUPER, Q, Screenshot, exec, omarchy-capture-screenshot
bindd = SUPER, E, Emoji picker, exec, omarchy-launch-walker -m symbols
bindd = SUPER, R, Show key bindings, exec, omarchy-menu-keybindings
bindd = SUPER, I, Wifi controls, exec, omarchy-launch-wifi
bind = SUPER, P, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ && swayosd-client --output-volume raise
bindd = SUPER, C, Copy history, exec, omarchy-launch-walker -m clipboard
bindd = SUPER, B, Bluetooth controls, exec, omarchy-launch-bluetooth
bindd = SUPER, N, Toggle nightlight, exec, omarchy-toggle-nightlight
bind = SUPER, M, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && swayosd-client --output-volume lower
